config:
  aws:region: us-east-1
  zenobase:certificateArn: arn:aws:acm:us-east-1:694665597187:certificate/aa7538d0-05ca-4459-9fc2-ad2301efa13d
  zenobase:keyPairName: zeno
  zenobase:instanceType: t4g.medium
  zenobase:playHeap: 2g
  zenobase:hostname: "https://zenobase.com"
  zenobase:apiHostname: "https://api.zenobase.com"
  zenobase:oauthHostname: "https://zenobase.com"
  zenobase:sesIdentity: info@zenobase.com
  zenobase:esSnapshotBucket: zeno-snapshots
  zenobase:osDomainName: zeno-opensearch-119
  zenobase:esReplayHost: ""
  zenobase:esRebuildHost: ""
  zenobase:playImageTag: "87a4c76734b82d20fae9afedea1cfc78dd425633"
  zenobase:deployTarget: blue
  zenobase:activeTargetGroup: blue
