version: 2
jobs:
  build:
    working_directory: ~/zenobase
    environment:
      SBT_VERSION: 0.13.18
    docker:
    - image: openjdk:8
    steps:
    - run:
        name: Installing packages
        command: |
          apt-get update && apt-get install -y curl python3-pip
          apt-get clean && apt-get autoclean
          curl -Ls https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz | tar xvz -C /usr/share/
          update-alternatives --install /usr/local/bin/sbt sbt /usr/share/sbt/bin/sbt 20
          sbt about
          pip install awscli
    - checkout
    - restore_cache:
        key: sbt-cache
    - run:
        name: Building and testing
        command: sbt 'test-only *Test'
    - save_cache:
        key: sbt-cache
        paths:
        - ~/.ivy2
        - ~/.sbt
        - ~/.m2
    - deploy:
        name: Publishing to S3
        command: |
          sbt universal:package-zip-tarball
          aws s3 cp target/universal/zenobase-SNAPSHOT.tgz s3://zeno-builds/zenobase-$CIRCLE_BUILD_NUM.tgz
