#! /bin/sh

APP_NAME="Play"
APP_PATH="/var/play"
APP_USER="play"

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting $APP_NAME"
		sudo -u $APP_USER $APP_PATH/start -Dconfig.file=/etc/play.conf >/dev/null &
		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping $APP_NAME"
		kill `cat $APP_PATH/RUNNING_PID`
		log_end_msg 0
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		;;
	*)
		log_success_msg "Usage: play {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0
