services:
  play:
    image: ${ECR_REGISTRY}/zenobase-play:${PLAY_IMAGE_TAG:-latest}
    network_mode: host
    volumes:
      - /etc/play/prod.conf:/etc/play/prod.conf:ro
      - ./play/config/logback-play.xml:/etc/play/logback.xml:ro
      - ./play/config/enableLegacyTLS.security:/etc/play/enableLegacyTLS.security:ro
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST:-http://localhost:9200}
      - OPENSEARCH_SNAPSHOT_BUCKET=${OPENSEARCH_SNAPSHOT_BUCKET:-}
      - OPENSEARCH_SNAPSHOT_ROLE_ARN=${OPENSEARCH_SNAPSHOT_ROLE_ARN:-}
      - OPENSEARCH_REPLAY=${OPENSEARCH_REPLAY:-}
      - OPENSEARCH_REPLAY_PARALLELISM=${OPENSEARCH_REPLAY_PARALLELISM:-0}
      - OPENSEARCH_REBUILD=${OPENSEARCH_REBUILD:-}
      - OPENSEARCH_REBUILD_PARALLELISM=${OPENSEARCH_REBUILD_PARALLELISM:-0}
      - HOSTNAME=${HOSTNAME:-http://localhost:9000}
      - API_HOSTNAME=${API_HOSTNAME:-http://localhost:9000}
      - OAUTH_HOSTNAME=${OAUTH_HOSTNAME:-https://zenobase.com}
    restart: unless-stopped
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION:-us-east-1}
        awslogs-group: /zenobase/play
        tag: play
