services:
  opensearch:
    image: zenobase-opensearch:latest
    pull_policy: never
    ports:
      - "9200:9200"
    volumes:
      - ../data/opensearch:/usr/share/opensearch/data
      - ../data/snapshots:/usr/share/opensearch/data/snapshots
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - plugins.security.disabled=true
      - path.repo=/usr/share/opensearch/data/snapshots
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
      memlock:
        soft: -1
        hard: -1

  play:
    image: zenobase-play:latest
    pull_policy: never
    build:
      context: ..
      dockerfile: docker/play/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./play/config/play.conf:/etc/play/prod.conf:ro
      - ./play/config/logback-play.xml:/etc/play/logback.xml:ro
      - ./play/config/enableLegacyTLS.security:/etc/play/enableLegacyTLS.security:ro
      - ../conf/local.conf:/etc/play/local.conf:ro
    environment:
      - JAVA_HEAP=1g
      - ES_SNAPSHOT_BUCKET=
      - ES_SNAPSHOT_REPOSITORY=
    depends_on:
      opensearch:
        condition: service_healthy
