name: 'Setup SBT'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 8
    - id: cache-sbt
      uses: actions/cache@v5
      with:
        path: ~/sbt
        key: sbt-install-0.13.18
    - if: steps.cache-sbt.outputs.cache-hit != 'true'
      shell: bash
      run: curl -Ls https://github.com/sbt/sbt/releases/download/v0.13.18/sbt-0.13.18.tgz | tar xvz -C ~/
    - shell: bash
      run: echo "$HOME/sbt/bin" >> $GITHUB_PATH
    - uses: actions/cache@v5
      with:
        path: |
          ~/.ivy2
          ~/.sbt
          ~/.m2
        key: sbt-${{ hashFiles('build.sbt', 'project/build.properties', 'project/plugins.sbt') }}
        restore-keys: sbt-
